// src/components/Footer.svelte
<script>
    const config = window.yukitoki.config;
</script>

<footer class="bg-blurple-600 text-center py-10">
    <a href="/"><h1 class="text-white text-2xl cursor-pointer font-bold">{config.FOOTER.HEADER}</h1></a>
    <p class="text-lg text-white mb-3">{config.FOOTER.DESCRIPTION}</p>

    <hr class="w-1/3 mx-auto border-t-2 border-gray-200 py-3" />

    <p class="text-white">Memer API - &copy; <a class="hover:text-gray-300" href="https://github.com/DevSnowflake">Snowflake Studio ❄</a> - {new Date().getFullYear()}</p>
</footer>

// components/Footer.jsx
import { SITE_NAME, FOOTER_DESCRIPTION } from "../config";
import Link from "next/link";

export default function Footer() {
    return (
        <div className="bg-gray-800 py-10">
            <div className="container mx-auto">
                <h1 className="text-center text-gray-300 text-2xl">
                    <Link href="/">{SITE_NAME}</Link>
                </h1>
                <p className="text-center text-gray-300">{FOOTER_DESCRIPTION}</p>
                <p className="text-center text-gray-300 mt-10">
                    © Memer Api - {new Date().getFullYear()}
                </p>
                <p className="text-center text-gray-300 mt-10">
                    Website By - <a href="https://github.com/DevSnowflake">Snowflake Studio ❄</a>
                </p>
            </div>
        </div>
    );
}
